name: Build-Releases
on:
  release:
    types:
      - created
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'
    - name: Display the Release tag
      run: echo ${{ github.event.release.tag_name }}

    - name: Build for all platforms
      run: |
        mkdir -p dist
        platforms=("windows/amd64" "linux/amd64" "darwin/amd64" "darwin/arm64" "linux/arm64" "windows/arm64")
        for platform in "${platforms[@]}"; do
          os=$(echo $platform | cut -d'/' -f1)
          arch=$(echo $platform | cut -d'/' -f2)
          output="dist/nicetube-$os-$arch"
          [ "$os" == "windows" ] && output+=".exe"
          GOOS=$os GOARCH=$arch go build -o $output ./app
        done
    - name: Upload release assets
      run: |
        for file in dist/*; do
          echo "Uploading $file..."
          gh release upload "${{ github.event.release.tag_name }}" "$file" --clobber
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
